services:

  frontend:
    build:
      context: ./kitsune-frontend
      network: "host"
    ports:
      - "8080:8080"
    depends_on:
      - backend
    network_mode: "host"

  backend:
    build: ./kitsuneC2
    expose:
      - "7331"
    network_mode: "host"
