services:
  frontend:
    build:
      context: ./kitsune-frontend
      network: "host"
    depends_on:
      - backend
    network_mode: "host"

  backend:
    build: ./kitsuneC2
    network_mode: "host"
    cap_add:
      - NET_BIND_SERVICE
    user: "appuser"
